def extraer_datos(datos_hex):
    """
    Extrae los datos del paquete en formato hexadecimal.
    Por ahora retorna valores por defecto "Not Found" para cada campo,
    listos para ser reemplazados con lógica de decodificación real.
    """
    
    campos = {
        "NUM": "Not Found",
        "SAC": "Not Found",
        "SIC": "Not Found",
        "TIME": "Not Found",
        "TIME(s)": "Not Found",
        "LAT": "Not Found",
        "LON": "Not Found",
        "H": "Not Found",
        "TYP_020": "Not Found",
        "SIM_020": "Not Found",
        "RDP_020": "Not Found",
        "SPI_020": "Not Found",
        "RAB_020": "Not Found",
        "TST_020": "Not Found",
        "ERR_020": "Not Found",
        "XPP_020": "Not Found",
        "ME_020": "Not Found",
        "MI_020": "Not Found",
        "FOE_FRI_020": "Not Found",
        "RHO": "Not Found",
        "THETA": "Not Found",
        "V_070": "Not Found",
        "G_070": "Not Found",
        "MODE 3/A": "Not Found",
        "V_090": "Not Found",
        "G_090": "Not Found",
        "FL": "Not Found",
        "MODE C corrected": "Not Found",
        "SRL_130": "Not Found",
        "SSR_130": "Not Found",
        "SAM_130": "Not Found",
        "PRL_130": "Not Found",
        "PAM_130": "Not Found",
        "RPD_130": "Not Found",
        "APD_130": "Not Found",
        "TA": "Not Found",
        "TI": "Not Found",
        "MCP_ALT": "Not Found",
        "FMS_ALT": "Not Found",
        "BP": "Not Found",
        "VNAV": "Not Found",
        "ALT_HOLD": "Not Found",
        "APP": "Not Found",
        "TARGET_ALT_SOURCE": "Not Found",
        "RA": "Not Found",
        "TTA": "Not Found",
        "GS": "Not Found",
        "TAR": "Not Found",
        "TAS": "Not Found",
        "HDG": "Not Found",
        "IAS": "Not Found",
        "MACH": "Not Found",
        "BAR": "Not Found",
        "IVV": "Not Found",
        "TN": "Not Found",
        "X": "Not Found",
        "Y": "Not Found",
        "GS_KT": "Not Found",
        "HEADING": "Not Found",
        "CNF_170": "Not Found",
        "RAD_170": "Not Found",
        "DOU_170": "Not Found",
        "MAH_170": "Not Found",
        "CDM_170": "Not Found",
        "TRE_170": "Not Found",
        "GHO_170": "Not Found",
        "SUP_170": "Not Found",
        "TCC_170": "Not Found",
        "HEIGHT": "Not Found",
        "COM_230": "Not Found",
        "STAT_230": "Not Found",
        "SI_230": "Not Found",
        "MSCC_230": "Not Found",
        "ARC_230": "Not Found",
        "AIC_230": "Not Found",
        "B1A_230": "Not Found",
        "B1B_230": "Not Found"
    }

    # Aquí puedes empezar a implementar la lógica para llenar cada campo con datos reales.
    # Por ejemplo:
    # campos["TIME"] = convertir_tiempo(hex_string[10:14])
    # campos["LAT"] = convertir_latitud(hex_string[20:26])
    # etc...

    return campos
